messages:
  help:
    brutalMode: "<gold>Brutal mode: If all items of a material should be removed, not only one itemstack. Usage: /li brutal [true | false]</gold>"
    eChestRemove: "<gold>EChest Remove: If items to remove should include echest items\n Usage: /li ecr [true | false]</gold>"
    enabled: "<gold>Enabled: If the plugin is enabled or not. Usage: /li enabled [true | false]</gold>"
  reload: "<green>Reloaded config file.</green>"
  noPerms: "<red>You don't have permission to use this command.</red>"
  success: "<green>Command successful!</green>"
  updateFound: "<green>Lost Items can be updated at https://www.curseforge.com/minecraft/bukkit-plugins/lost-items/\n 
  If you don't see the update yet, come back in 24-48 hours. It should be ready by then.</green>"

options:
  brutalMode: false
  eChestRemove: true
  enabled: true

updateCheck: true